---
driver:
  name: vagrant
  network:
  synced_folders:
    - [".", "/vagrant", "create: true"]

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1

platforms:
  - name: centos-6.6
    driver_config:
      box: chef/centos-6.6
  - name: centos-6.7
    driver_config:
      box: bento/centos-6.7
  - name: centos-7.1
    driver_config:
      box: bento/centos-7.1
  - name: oracle-66
    driver_config:
      box: box-cutter/ol66
  - name: oracle-72
    driver_config:
      box: box-cutter/ol72
  - name: oracle-67
    driver_config:
      box: box-cutter/ol67
  - name: oracle-ol66-i386
    driver_config:
      box: box-cutter/ol66-i386

suites:
  - name: default
    data_bags_path: "test/data_bags"
    run_list:
      - recipe[jboss-eap]
    attributes:
